name=gnl-timer
version=1.0.0
author=gnoolson
maintainer=gnoolson@gmail.com
sentence=Timer library
paragraph=Timer library for Arduino
category=Other
url=https://github.com/gnoolson/gnl-timer
architectures=*
